spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aysdatabase
    username: aysuser
    password: aysuser
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect