spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aysdatabase
    username: aysuser
    password: aysuser
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      #mode: always
  servlet:
    multipart:
      enabled: true
      # tamaño de archivos de video de programas
      max-file-size: 2000MB
      max-request-size: 2000MB
ays:
  max-size: 199MB